sudo: false
dist: xenial
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
branches:
  only:
  - master
  - develop
env:
  - DJANGO="2.2"
  - DJANGO="master"
matrix:
  allow_failures:
    - python: "3.5"
      env: DJANGO="master"
    - python: "3.6"
      env: DJANGO="master"
    - python: "3.7"
      env: DJANGO="master"
install: pip install -e ".[debug]"
script: ./manage.py test
