sudo: false
dist: xenial
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
branches:
  only:
  - master
  - develop
env:
  - DJANGO_DEP="django==2.2"
  - DJANGO_DEP="https://github.com/django/django.git"
matrix:
  allow_failures:
    - python: "3.5"
      env: DJANGO_DEP="https://github.com/django/django.git"
    - python: "3.6"
      env: DJANGO_DEP="https://github.com/django/django.git"
    - python: "3.7"
      env: DJANGO_DEP="https://github.com/django/django.git"
install:
  - pip install poetry
  - poetry install
  - poetry run pip install "${DJANGO_DEP}"
script: poetry run ./manage.py test
