sudo: false
dist: xenial
language: python
services:
  - postgresql
  - mysql
before_script:
  - psql -c 'create database spkcspider_tests;' -U postgres
  - mysql -e 'CREATE DATABASE spkcspider_tests;'
python:
  - "3.6"
  - "3.7"
  - "3.8"
branches:
  only:
  - master
  - develop
env:
  - DJANGO_DEP=django22
  - DJANGO_DEP=django30
  - DJANGO_DEP=djangomaster
matrix:
  exclude:
    - python: "3.5"
      env: DJANGO_DEP=djangomaster
  allow_failures:
    - env: DJANGO_DEP=djangomaster
install:
  - pip install tox
script: tox -e "py$(echo ${TRAVIS_PYTHON_VERSION} | tr -d .)-$DJANGO_DEP-{sqlite3,mysql,postgresql}"

cache: pip
