version: '3'

services:
  app:
    build: .
    command: bash -c "./manage.py migrate; ./manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
    ports:
      - "8000:8000"
