[tool.poetry]
name = "spkcspider"
description = "Safe online identity"
version = "0.1"
authors = ["Alexander Kaftan"]
homepage = "https://spkcspider.net"
readme = "README.md"
repository = ""

[tool.poetry.dependencies]
python = ">=3.5"
django = '>=2'
django-simple-jsonfield = '*'
requests = '*'
certifi = '*'
bleach = '*'
rdflib = '*'
html5lib = '*'
cryptography = "*"
django-ranged-response = "*"
django-widget-tweaks = "*"

[tool.poetry.dev-dependencies]
django-extensions = '*'
Werkzeug = '*'
pyOpenSSL = '*'
django-webtest = '*'
django-simple-captcha = "*"
WSGIProxy2 = "*"

[tool.poetry.extras]
mysql = ["mysqlclient"]
pgsql = ["psycopg-binary"]
captcha = ["django-simple-captcha"]


[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
